def shopapi
def shopui
def website

pipeline {
  options {
    skipStagesAfterUnstable()
    buildDiscarder(logRotator(numToKeepStr: '5'))
  }

  agent {
    kubernetes {
      yamlFile 'build-pod.yaml'
      defaultContainer 'devops-tools'      
    }
  }

  stages {
    stage('Clone Bookstore Repository') { 
      steps { 
        script {
          checkout scm
        }
      }
    }

    stage('Build shop-api Image') { 
      steps {
        dir('ci-pipelines/bookstore-ci/shop-api') {
          script {
            shopapi = docker.build("opeomotayo/shop-api")
          }
        }
      }
    }
    stage('Build shop-ui Image') { 
      steps {
        dir('ci-pipelines/bookstore-ci/shop-ui') {
          script {
            shopui = docker.build("opeomotayo/shop-ui")
          }
        }
      }
    }
    stage('Build website Image') { 
      steps {
        dir('ci-pipelines/bookstore-ci/website') {
          script {
            website = docker.build("opeomotayo/website")
          }
        }
      }
    }

    stage('SonarQube analysis') {
        tools {
          sonarQube 'sonarqube-scanner-4.8.0' //This is the scanner you added
        }
        steps{
          dir('ci-pipelines/bookstore-ci/shop-api') {
        // withSonarQubeEnv('sonarqube-8.9.10') { 
        // // If you have configured more than one global server connection, you can specify its name
        // // sh "${scannerHome}/bin/sonar-scanner"
        // sh "mvn sonar:sonar"
          withSonarQubeEnv('sonarqube-8.9.10') {  //This is the server you added
            sh "${scannerHome}/bin/sonar-scanner"
          }
        // }
        }
      }
    }

    stage('Publish to Nexus') {
        steps { 
            script {  
                if (currentBuild.result == null || currentBuild.result == 'SUCCESS') {     
                  docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-creds') {
                    shopapi.push("${env.BUILD_NUMBER}")
                    shopui.push("${env.BUILD_NUMBER}")
                    website.push("${env.BUILD_NUMBER}")
                  }
                }
            }
        }
    }
    
    stage('Trigger bookstore-cd Job') {
      steps { 
        script {  
          sh "printenv"
          echo "triggering the pipeline that updates deployment image tag"
          // paramAValue = "paramAValue"
          // paramBValue = "paramBValue"
          //  build job: 'html-blog-cd', wait: false, parameters: [string(name: 'HELLO', value: "${env.BUILD_NUMBER}")]
          // build job: 'downstream-freestyle', parameters: [[$class: 'StringParameterValue', name: 'ParamA', value: paramAValue], [$class: 'StringParameterValue', name: 'ParamB', value: paramBValue]]
          def job = build job: 'bookstore-cd', parameters: [[$class: 'StringParameterValue', name: 'DOCKERTAG', value: "${env.BUILD_NUMBER}"]]
        }
      }    
    }
  }
}
