apiVersion: v1
kind: Pod
metadata:
spec:
  serviceAccountName: jenkins # a service account that can deploy to all namespaces
  # securityContext:
  #   runAsUser: 0
  containers:  # a list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: kubectl
      image: gcr.io/cloud-builders/kubectl
      command:
        - cat
      tty: true
    - name: node
      image: node:10
      command:
        - cat
      tty: true
    - name: devops-tools
      image: opeomotayo/devops-tools:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
      command:
        - cat
      tty: true
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 500m
          memory: 500Mi
    - name: docker
      image: docker:latest
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine
    - name: security-tools
      image: opeomotayo/security-tools:latest
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock
      command:
        - cat
      tty: true
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 500m
          memory: 500Mi
    - name: aqua
      image: opeomotayo/aqua:latest
      command:
        - cat
      tty: true
    - name: maven
      image: maven:3.8.1-jdk-8
      command:
        - cat
      tty: true
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
  