apiVersion: v1
kind: Pod
metadata:
spec:
  serviceAccountName: jenkins # a service account that can deploy to all namespaces
  # securityContext:
  #   runAsUser: 0
  containers:  # a list of containers that you want present for your build, you can define a default container in the Jenkinsfile
  - name: devops-tools
    image: opeomotayo/devops-tools:latest
    imagePullPolicy: Always
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 500Mi
  - name: security-tools
    image: opeomotayo/security-tools:latest
    imagePullPolicy: Always
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 500Mi
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock