def app

pipeline {
    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
    }

    agent {
        kubernetes {
            // label "-${UUID.randomUUID()}"
            yamlFile 'build-pod.yaml'
            defaultContainer 'devops-tools'      
        }
    }

    stages {

        stage('Tesing...') {
            steps {
                sh "ls -la"
                sh "pwd"
            }
        }

        // stage('Build image') {
        //     app = docker.build("opeomotayo/hello-world")
        // }

        // stage('Test image') {
        //     app.inside {
        //         sh 'echo "Tests passed"'
        //     }
        // }

        // stage('Push image') {         
        //     docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-access') {
        //         app.push("${env.BUILD_NUMBER}")
        //     }
        // }
        
        // stage('Trigger ManifestUpdate') {
        //     echo "triggering updatemanifestjob"
        //     build job: 'updatemanifest', parameters: [string(name: 'DOCKERTAG', value: env.BUILD_NUMBER)]
        // }
    }
}
