apiVersion: v1
kind: Pod
metadata:
spec:
  serviceAccountName: jenkins
  # securityContext:
  #   runAsUser: 0
  containers: 
  - name: devops-tools
    image: opeomotayo/devops-tools:latest
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 500Mi
  - name: security-tools
    image: opeomotayo/security-tools:latest
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 500Mi
